version: '1.0.0'
services:
  iris:
    build:
      context: .
    image: iris:$VERSION
    container_name: iris
    ports:
      - "3801:3838"
    environment:
      - TARGET=$TARGET
    restart: unless-stopped
